### ISSUE TITLE
Make it compatible with Nim-random

### ISSUE THREAD

**Issue by andreaferretti** [pragmagic/isaac#1]
Any chance you could make this API-compatible with [Nim-random](https://github.com/BlaXpirit/nim-random)? In this way, one could use the operations defined there with Isaac.

It is enough to implement [a single function](https://github.com/BlaXpirit/nim-random#custom-rngs)

**Comment by endragor** [comment]
Sorry for the delay. GitHub didn't set me up to watch my own repo, so I missed this issue :/
